### ISSUE TITLE
Option to unlatch the door

### ISSUE THREAD

**Issue by leranp** [uriyacovy/ESPHome_nuki_lock#1]
Thank you for this addon, it works great and saves me 100€ for the bridge.
Are there any options to add unlatch the door?
This option is in the NukiBleEsp32 library

**Comment by uriyacovy** [comment]
Hi @leranp, thank you for the positive feedback.
I can try to implement this based on "open" service as defined in the documentation of the [lock integration](https://www.home-assistant.io/integrations/lock/).

**Comment by uriyacovy** [comment]
Hi @leranp, open was implemented. Please try and let me know if it works for you.

**Comment by marcor78** [comment]
> Hi @leranp, open was implemented. Please try and let me know if it works for you.

Hi! I'm very interested in this option too. I'm trying both via command "open" on mqtt and via home assistant service call, but still no joy. I also cleaned build and reinstalled firmware on the esp32, but it seems nothing changed about the command "open". Is there something else I should do to try this new feature? Thanks!!!

**Comment by marcor78** [comment]
this is the log after rebooting the esp32 with the new install:

[19:23:57][D][lock:055]: 'Nuki Lock': Sending state LOCKED
[19:24:09][D][lock:055]: 'Nuki Lock': Sending state UNLOCKED
[19:24:26][I][nukilock.lock :022]: event notified 0
[19:24:29][I][nukilock.lock :034]: Bat state: 0xc8, Bat crit: 1, Bat perc:100 lock state: 3 19:24:32
[19:24:29][D][sensor:125]: 'Nuki Battery Level': Sending state 100.00000 % with 0 decimals of accuracy
[19:24:35][W][lock:046]: 'Nuki Lock' Does not support Open.
[19:25:05][W][lock:046]: 'Nuki Lock' Does not support Open.
[19:25:30][I][ota:105]: Boot seems successful, resetting boot loop counter.
[19:25:30][D][esp32.preferences:114]: Saving preferences to flash...

**Comment by leranp** [comment]
> > Hi @leranp, open was implemented. Please try and let me know if it works for you.
> 
> Hi! I'm very interested in this option too. I'm trying both via command "open" on mqtt and via home assistant service call, but still no joy. I also cleaned build and reinstalled firmware on the esp32, but it seems nothing changed about the command "open". Is there something else I should do to try this new feature? Thanks!!!

I have the same results, open command doesn't do anything

**Comment by uriyacovy** [comment]
@marcor78, @leranp, I'm not sure how you've cleaned the build, but esphome clean does not delete the external components folder. Please delete manually .esphome/external_components, compile and run again.

**Comment by leranp** [comment]
> @marcor78, @leranp, I'm not sure how you've cleaned the build, but esphome clean does not delete the external components folder. Please delete manually .esphome/external_components, compile and run again.

You are right, cleaning the compile folder was fixed the problem and now the open command is working great, thanks again

**Comment by uriyacovy** [comment]
Great to hear.
@marcor78, waiting also for your feedback. Please confirm that it works, or reopen the issue if it doesn't.

**Comment by marcor78** [comment]
> Great to hear. @marcor78, waiting also for your feedback. Please confirm that it works, or reopen the issue if it doesn't.

Just tried again and it works flawlessly! In my case, deleting .esphome/external_components wasn't enough. I had to also manually delete the esp32 specific content in folder .esphome/build/xxxx, then compiling again and reflash the esp32. But then finally everything works as expected. I still can't run the open command in home assistant (service lock.open yield an API error in Nodered), but the command given through mqtt (nuki-lock/lock/nuki_lock/command open) works perfectly. Thanks so much!
